name: Produccion

# Definimos los servicios que se ejecutarán en los contenedores Docker.
services:
  java:
    image: buenaspracticas:0.0.1-SNAPSHOT
    ports:
      - '80:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/produccion
      SPRING_DATASOURCE_USERNAME: produser
      SPRING_DATASOURCE_PASSWORD: prodpassword
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'produccion'
      MYSQL_USER: 'produser'
      MYSQL_PASSWORD: 'prodpassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always


